import { useMemo, useState } from "react";
import {
  applyRsList,
  combinedRows,
  commonRows,
  LIST_DEFS,
  redCloudOrDtbRows,
  RS_LIST_DEFS,
} from "../engine";
import type { ScreenResult, SummaryRow } from "../engine/types";
import { downloadCsv } from "../export/toCsv";
import { downloadExcel } from "../export/toExcel";
import { ACTION_COLUMNS, RESULT_COLUMNS, RS_COLUMNS, SUMMARY_COLUMNS, type ColumnDef } from "./columns";
import { ResultsTable } from "./ResultsTable";
import type { ViewMode } from "../markets";

interface Tab {
  key: string;
  title: string;
  criteria: string;
  rows: SummaryRow[];
  columns: ColumnDef[];
  note?: string;
}

export function ResultsView({ result, views = "full" }: { result: ScreenResult; views?: ViewMode }) {
  const tabs: Tab[] = useMemo(() => {
    const summaryTab: Tab = {
      key: "SUMMARY",
      title: "Summary Study",
      criteria: "The full joined table — every screened stock with all computed metrics, ranks and detail columns.",
      rows: [...result.summary].sort((a, b) => a.scrip.localeCompare(b.scrip)),
      columns: SUMMARY_COLUMNS,
    };
    if (views === "summary") return [summaryTab];
    return [
      {
        key: "COMMON",
        title: "High Momentum",
        criteria: "Stocks appearing in all three lists (A ∩ B ∩ C) — the highest-conviction signals.",
        rows: commonRows(result.lists),
        columns: RESULT_COLUMNS,
      },
      {
        key: "REDDTB",
        title: "Red Cloud / DTB",
        criteria:
          "From the combined B∪C list — stocks with a Red 0.15 cloud OR an active DTB level (> 0). Columns G–X.",
        rows: redCloudOrDtbRows(result.lists),
        columns: ACTION_COLUMNS,
        note: "Y/Q/M ranks need the external ranking workbook (not part of the daily files), so they show as “—”.",
      },
      {
        key: "COMBINED",
        title: "Combined (B∪C)",
        criteria: "The working list — unique union of List B and List C (duplicates removed).",
        rows: combinedRows(result.lists),
        columns: RESULT_COLUMNS,
      },
      ...RS_LIST_DEFS.map((d) => ({
        key: d.key,
        title: d.title,
        criteria: d.criteria,
        rows: applyRsList(d, result.summary),
        columns: RS_COLUMNS,
      })),
      ...LIST_DEFS.map((d) => ({
        key: d.key,
        title: `${d.key}: ${d.title}`,
        criteria: d.criteria,
        rows: result.lists[d.key],
        columns: RESULT_COLUMNS,
      })),
      summaryTab,
    ];
  }, [result, views]);

  const [active, setActive] = useState<string>(views === "summary" ? "SUMMARY" : "COMMON");
  const tab = tabs.find((t) => t.key === active) ?? tabs[0];

  return (
    <div className="panel">
      <h2>Stocks in Action</h2>
      <div className="muted" style={{ marginTop: -8, marginBottom: 12 }}>
        {result.summary.length} stocks screened across the three filters.
      </div>
      <div className="tabs">
        {tabs.map((t) => (
          <button
            key={t.key}
            className={`tab ${t.key === active ? "active" : ""}`}
            onClick={() => setActive(t.key)}
          >
            {t.title}
            <span className="badge">{t.rows.length}</span>
          </button>
        ))}
      </div>

      <div className="criteria">{tab.criteria}</div>

      <div className="actions" style={{ marginBottom: 12 }}>
        <button
          className="secondary"
          onClick={() => downloadCsv(`HyperScan ${tab.key}.csv`, tab.rows, tab.columns)}
        >
          Download {tab.key} CSV
        </button>
        <button className="secondary" onClick={() => downloadExcel(result)}>
          Download Excel (all views)
        </button>
      </div>

      <ResultsTable rows={tab.rows} columns={tab.columns} />

      {tab.note && (
        <div className="muted" style={{ marginTop: 8, fontSize: 12 }}>
          {tab.note}
        </div>
      )}

      <p className="disclaimer">
        <b>Disclaimer:</b> HyperScan is a technical screening and research tool. The stocks shown
        are generated by automated filters and are for informational and educational purposes only
        — they are not investment advice, nor a recommendation or solicitation to buy or sell any
        security. Markets carry risk; please do your own research or consult a SEBI-registered
        advisor before making any trading decision.
      </p>
    </div>
  );
}
