"""Map the scanner's abbreviated sector-index names to NSE's official index names
(as they appear in the NSE Index Bhavcopy `ind_close_all`). Keys and values are UPPERCASE
so matching is case-insensitive. Names not in the table are used as-is (already match)."""

SECTOR_TO_NSE = {
    "NIFTY CONSR DURBL": "NIFTY CONSUMER DURABLES",
    "NIFTY HEALTHCARE": "NIFTY HEALTHCARE INDEX",
    "NIFTY IND DIGITAL": "NIFTY INDIA DIGITAL",
    "NIFTY INDIA MFG": "NIFTY INDIA MANUFACTURING",
    "NIFTY OIL AND GAS": "NIFTY OIL & GAS",
    "NIFTY CAPITAL MKT": "NIFTY CAPITAL MARKETS",
    "NIFTY CONSUMPTION": "NIFTY INDIA CONSUMPTION",
    "NIFTY COREHOUSING": "NIFTY CORE HOUSING",
    "NIFTY CORP MAATR": "NIFTY INDIA SELECT 5 CORPORATE GROUPS (MAATR)",
    "NIFTY EV": "NIFTY EV & NEW AGE AUTOMOTIVE",
    "NIFTY FIN SERVICE": "NIFTY FINANCIAL SERVICES",
    "NIFTY FINSEREXBNK": "NIFTY FINANCIAL SERVICES EX-BANK",
    "NIFTY FINSRV25 50": "NIFTY FINANCIAL SERVICES 25/50",
    "NIFTY IND DEFENCE": "NIFTY INDIA DEFENCE",
    "NIFTY IND TOURISM": "NIFTY INDIA TOURISM",
    "NIFTY INFRA": "NIFTY INFRASTRUCTURE",
    "NIFTY INFRALOG": "NIFTY INDIA INFRASTRUCTURE & LOGISTICS",
    "NIFTY INTERNET": "NIFTY INDIA INTERNET",
    "NIFTY MS FIN SERV": "NIFTY MIDSMALL FINANCIAL SERVICES",
    "NIFTY MS IT TELCM": "NIFTY MIDSMALL IT & TELECOM",
    "NIFTY MS IND CONS": "NIFTY MIDSMALL INDIA CONSUMPTION",
    "NIFTY MIDSML HLTH": "NIFTY MIDSMALL HEALTHCARE",
    "NIFTY NEW CONSUMP": "NIFTY INDIA NEW AGE CONSUMPTION",
    "NIFTY NONCYC CONS": "NIFTY NON-CYCLICAL CONSUMER",
    "NIFTY PVT BANK": "NIFTY PRIVATE BANK",
    "NIFTY SERV SECTOR": "NIFTY SERVICES SECTOR",
    "NIFTY TRANS LOGIS": "NIFTY TRANSPORTATION & LOGISTICS",
}


def to_nse(name: str) -> str:
    u = (name or "").strip().upper()
    return SECTOR_TO_NSE.get(u, u)
